# utils/ai_image_detector.py

import torch
from transformers import pipeline
from PIL import Image

print("🔄 Loading AI image detection model...")

# Load AI detection model (local, free)
try:
    ai_detector = pipeline(
        "image-classification",
        model="umm-maybe/AI-image-detector",
        device=0 if torch.cuda.is_available() else -1
    )
    print("✅ AI image detector loaded")
except Exception as e:
    print(f"⚠️ Failed to load AI detector: {e}")
    ai_detector = None


def detect_ai_generated(image):
    """
    Detect if image was generated by AI (DALL-E, Midjourney, etc.)
    
    Args:
        image: PIL Image object
        
    Returns:
        dict with detection results
    """
    if not ai_detector:
        return {
            'is_ai': False,
            'confidence': 0.0,
            'score': 0.7,  # Neutral
            'info': '⚠️ AI detection unavailable',
            'warning': None
        }
    
    try:
        print("   🤖 Checking if image is AI-generated...")
        
        # Ensure image is RGB
        if image.mode != 'RGB':
            image = image.convert('RGB')
        
        # Resize for faster processing (model works best with smaller images)
        max_size = 512
        if image.width > max_size or image.height > max_size:
            image.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)
        
        # Run detection
        results = ai_detector(image)
        
        # Results format: [{'label': 'artificial', 'score': 0.95}, {'label': 'real', 'score': 0.05}]
        
        # Find AI/artificial result
        ai_result = next((r for r in results if r['label'].lower() in ['artificial', 'ai', 'fake']), None)
        real_result = next((r for r in results if r['label'].lower() in ['real', 'human']), None)
        
        if ai_result:
            ai_confidence = ai_result['score']
        elif real_result:
            ai_confidence = 1.0 - real_result['score']
        else:
            ai_confidence = 0.5
        
        print(f"   🤖 AI probability: {ai_confidence:.1%}")
        
        # Decision thresholds
        if ai_confidence > 0.7:
            # High confidence AI-generated
            return {
                'is_ai': True,
                'confidence': ai_confidence,
                'score': 0.1,  # Very low credibility
                'info': f'🚨 Image appears to be AI-generated',
                'warning': f'This image has {ai_confidence:.0%} probability of being AI-generated (DALL-E, Midjourney, Stable Diffusion, etc.)'
            }
        
        elif ai_confidence > 0.4:
            # Uncertain
            return {
                'is_ai': False,
                'confidence': ai_confidence,
                'score': 0.5,  # Neutral
                'info': f'⚠️ Uncertain ({ai_confidence:.0%} AI probability)',
                'warning': f'Image might be AI-generated ({ai_confidence:.0%} probability). Treat with caution.'
            }
        
        else:
            # Likely real photo
            return {
                'is_ai': False,
                'confidence': ai_confidence,
                'score': 0.9,  # High credibility
                'info': f'✅ Image appears to be real photo ({100-ai_confidence:.0%} confidence)',
                'warning': None
            }
    
    except Exception as e:
        print(f"   ⚠️ AI detection error: {e}")
        return {
            'is_ai': False,
            'confidence': 0.0,
            'score': 0.7,
            'info': f'⚠️ AI detection failed: {str(e)}',
            'warning': None
        }


def analyze_image_authenticity(image):
    """
    High-level function to check if image is authentic or AI-generated
    """
    return detect_ai_generated(image)